### ISSUE TITLE
[Question] Posting an file output

### ISSUE THREAD

**Issue by ghost** [JoseThen/comment-pr#3]
I have a question as to how to give json output as a comment? If it's even a "thing"? (Besides other actions)

**Comment by JoseThen** [comment]
Haven't tested for that yet but you should be able to use [Outputs](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter), here is a good example of it being used: [stackoverflow ](https://stackoverflow.com/questions/61919141/read-json-file-in-github-actions)

**Comment by JoseThen** [comment]
Actually, thanks for posting this here, gave me the motivation to add some updates : https://github.com/JoseThen/comment-pr/releases/tag/v1.1.0

Feel free to add any feedback, this `json` param may not be as full-featured due to how late I started 😄

**Comment by JoseThen** [comment]
One last comment, I noticed I may have mis-read the `file output`. How would this work when using the action something like 
```yaml
with:
  file: ./a-file-i-own.json
```
?

**Comment by 403-html** [comment]
@JoseThen yes! for using json file as output - something like  
\`\`\`  
uses: JoseThen/comment-pr@v1.2  
with:  
   file: ./generated.json  
   GITHUB\_TOKEN: ${{ secrets.GITHUB\_TOKEN }}  
\`\`\`  
but issue is old enough that I don't even remember the case, but I just remember it was json file generated in previous actions step

**Comment by JoseThen** [comment]
That sounds good, I'll start working on that functionality, give the people what they want ✊

**Comment by JoseThen** [comment]
I am superbly late here, but just want to point out this functionality now exists starting from https://github.com/JoseThen/comment-pr/releases/tag/v1.2.0

Please excuse me here for how long it took.
